# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

layout: default
name: Gadget Angel Voron Documentation
description: Voron Official and Community Documentation

# Set a path/url to a logo that will be displayed instead of the title
# set the logo to use during dark mode - set logo:
logo: "/images/voron_design_logo.png"
logo_dark: "/images/voron_design_logo.png"
# set the logo to use during light mode - set logo-light:
logo_light: "/images/voron_design_logo_light.png"

markdown: kramdown
remote_theme: pmarsceill/just-the-docs

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
# if you use toggle_color_scheme set color_scheme: dark and set toggle_color_scheme: light
color_scheme: dark
# To allow a toggle color scheme (also it adds a button to switch all pages) - set toggle_color_scheme: light
# To add a button to switch all pages to a different color scheme use toggle_color_scheme
toggle_color_scheme: light
# To display the toggle button only on one page - set toggle_page_url: "/"
# To display the toggle button on all pages - set toggle_page_url: nil
toggle_page_url: nil
# To toggle automatically when the system mode preference changes - set toggle_auto_mode: true, 
#    this will allow the user to use thier own "dark" and "light" color system color scheme
# To toggle the pages manually - set toggle_auto_mode: nil 
toggle_auto_mode: true 
# To set the button text for toggling and reverting - set toggle_text_1 and toggle_text_2
# toggle_text_1 is for light mode
toggle_text_1: "-> Return to the Dark Side"
# toggle_text_2 is for dark mode
toggle_text_2: "-> Color-Blind-Friendly Light Mode"

#exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
#, "docs/tests/"
#]

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  #heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  #previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  #preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  #preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  #tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  #rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# Enable or disable heading anchors
#heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Voron Documentation on GitHub":
    - "https://github.com/GadgetAngel/GA-Voron-Documentation"
  "VoronDesign Home":
    - "https://gadgetangel.org"

# Makes Aux links open in a new tab. Default is false
#aux_links_new_tab: true

# Sort order for navigation links (i.e.: case_sensitive, case_insensitive)
# nav_sort: case_insensitive # default, equivalent to nil
# nav_sort: case_sensitive # # Capital letters sorted before lowercase
#nav_sort: case_insensitive # default, equivalent to nil

# Back to top link
#back_to_top: true
#back_to_top_text: "Back to top"

# Footer content
# appears at the bottom of every page's main content
#footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"
footer_content: "Open Source Project by Voron Design Team. Distributed by an <a href=\"https://github.com/VoronDesign/Voron-Documentation/tree/main/LICENSE.txt\">GNU GENERAL PUBLIC LICENSE.</a>"

# Footer last edited timestamp
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
